services:
  command_service:
    container_name: springboot_cqrs_command
    ports:
    - 8181:8080


  query_service:
    container_name: springboot_cqrs_query
    ports:
    - 8182:8081


  frontend_service:
    container_name: react_mui_cqrs
    ports:
    - 80:3000
